# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: check-yaml
    -   id: check-added-large-files
        args: [--maxkb=2500]
    -   id: check-byte-order-marker
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: fix-encoding-pragma
    -   id: flake8
        args: [--max-line-length=90, "--ignore=E203,W503"]
        language_version: python3.7
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        language_version: python3.7
